[theme]
background = "#24273a"
primary = "#cad3f5"
secondary = "#a5adcb"
title = "#8bd5ca"
playing = "#a6da95"
playing_selected = "#a6da95"
playing_bg = "#363a4f"
highlight = "#f5a97f"
highlight_bg = "#494d64"
error = "#ed8796"
error_bg = "#363a4f"
statusbar = "#24273a"
statusbar_progress = "#8aadf4"
statusbar_bg = "#1e2030"
cmdline = "#cad3f5"
cmdline_bg = "#363a4f"
search_match = "#eed49f"
